<?php

/**
 * @file
 * Drupal Oppevara H5P Overrides module.
 */

function ov_h5p_overrides_h5p_semantics_alter(&$semantics, $machine_name, $major_version, $minor_version) {

  /*
   * Add new options for H5P Column dropdown
   */

  if ($machine_name == 'H5P.Column' && $major_version == 1) {
    array_push($semantics[0]->field->fields[0]->options,
      'H5P.ImageMultipleHotspotQuestion 1.0',
      'H5P.VisualMathInput 1.0',
      'H5P.VisualMathInput 0.1',
      'H5P.Geogebra 1.1',
      'H5P.GridChecker 1.0',
      'H5P.ImageSlider 1.0',
      'H5P.ImageJuxtaposition 1.1',
      'H5P.GuessTheAnswer 1.2',
      'H5P.MultipleChoiceDropDown 1.0',
      'H5P.Kekule 1.0',
      'H5P.KekuleReaction 1.0'
      );
    $semantics[0]->field->fields[0]->options = array_unique($semantics[0]->field->fields[0]->options);
  }

  /*
   * Add new content types for Question Set (Quiz) content type
   */

  if ($machine_name == 'H5P.QuestionSet' && $major_version == 1) {
    array_push($semantics[4]->field->options,
      'H5P.ImageMultipleHotspotQuestion 1.0',
      'H5P.ImageHotspots 1.5'
    );
    $semantics[4]->field->options = array_unique($semantics[4]->field->options);
  }

  /*
   *  Add sub, sup and eqneditor tags to certain content types
   */

  switch ($machine_name){
    case 'H5P.SingleChoiceSet':
      array_push($semantics[0]->field->fields[0]->tags,'sub','sup', 'eqneditor');
      array_push($semantics[0]->field->fields[1]->field->tags,'sub','sup', 'eqneditor');
      break;
    case 'H5P.DragText':
      array_push($semantics[0]->tags,'sub','sup');
      // Change field type from textarea to WYSIWYG!
      $semantics[1]->widget = 'html';
      $semantics[1]->tags = array('p','sub','sup');
      break;
    case 'H5P.AdvancedText':
      array_push($semantics[0]->tags,'sub','sup', 'eqneditor');
      break;
    case 'H5P.Text':
      array_push($semantics[0]->tags,'sub','sup', 'eqneditor');
      break;
    case 'H5P.Blanks':
      array_push($semantics[1]->tags,'sub','sup');
      array_push($semantics[2]->field->tags,'sub','sup', 'eqneditor');
      break;
    case 'H5P.MultiChoice':
      array_push($semantics[1]->tags,'eqneditor');
      array_push($semantics[2]->field->fields[0]->tags,'eqneditor');
      break;
    case 'H5P.MarkTheWords':
      array_push($semantics[0]->tags,'sub','sup');
      array_push($semantics[1]->tags,'sub','sup');
      break;
    case 'H5P.TrueFalse':
      array_push($semantics[1]->tags,'eqneditor');
      break;
    case 'H5P.ImageMultipleHotspotQuestion':
      // Change field type from textarea to WYSIWYG!
      $semantics[0]->fields[1]->fields[0]->widget = 'html';
      $semantics[0]->fields[1]->fields[0]->tags = array('p','sub','sup', 'eqneditor');
      break;
  }
}

function ov_h5p_overrides_h5p_scripts_alter(&$scripts, $libraries, $mode) {
  if (isset($libraries['H5P.SingleChoiceSet']) || isset($libraries['H5P.MultiChoice']) || isset($libraries['H5P.Blanks']) || isset($libraries['H5P.AdvancedText']) || isset($libraries['H5P.Text']) || isset($libraries['H5P.VisualMathInput']) || isset($libraries['H5P.ImageHotspots']) || isset($libraries['H5P.TrueFalse']) || isset($libraries['H5P.ImageMultipleHotspotQuestion']) || isset($libraries['H5P.DragText']) ) {
    $scripts[] = (object) array(
      'path' => 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?delayStartupUntil=configured&config=TeX-AMS_CHTML,' . $GLOBALS['base_url'] . '/ov_h5p/mathjax_conf.js',
      'version' => ''
    );

    $scripts[] = (object) array(
      'path' => drupal_get_path('module', 'ov_h5p_overrides') . '/math_jax_hacks.js',
      'version' => '?v=1.0.0'
    );

    if(isset($libraries['H5P.Blanks']) && $libraries['H5P.Blanks']['majorVersion'] == "1" && $libraries['H5P.Blanks']['minorVersion'] == "10"){
      $scripts[] = (object) array(
        'path' => drupal_get_path('module', 'ov_h5p_overrides') . '/h5p-blanks-xapi-override.js',
        'version' => '?v=1.0.0'
      );
    }

    if(isset($libraries['H5P.ImageHotspots']) && $libraries['H5P.ImageHotspots']['majorVersion'] == "1" && $libraries['H5P.ImageHotspots']['minorVersion'] <= "7"){
      $scripts[] = (object) array(
          'path' => drupal_get_path('module', 'ov_h5p_overrides') . '/h5p-image-hotspots-override.js',
          'version' => '?v=1.0.0'
      );
    }
      
    if (isset($libraries['H5P.CoursePresentation']) && isset($libraries['H5P.InteractiveVideo']) && $libraries['H5P.CoursePresentation']['majorVersion'] == "1") {
      $scripts[] = (object) array(
          'path' => drupal_get_path('module', 'ov_h5p_overrides') . '/h5p-course-presentation-override.js',
          'version' => '?v=1.0.0'
      );
    }
  }

  if($mode == "iframe" || $mode = "external"){
      $scripts[] = (object) array(
          'path' => drupal_get_path('module', 'ov_h5p_overrides') . '/h5p-base-target-override.js',
          'version' => '?v=1.0.0'
      );

      $scripts[] = (object) array(
          'path' => drupal_get_path('module', 'ov_h5p_overrides') . '/h5p-image-max-height-override.js',
          'version' => '?v=1.0.0'
      );

  }
}


/*
 *  Declare custom endpoint for mathjax config file for CDN
 */
function ov_h5p_overrides_menu() {
  $items = array();

  $items['ov_h5p/mathjax_conf.js'] = array(
    'page callback' => 'ov_h5p_overrides_page_callback',
    'access callback' => TRUE, // Allow access to any user
    'type' => MENU_CALLBACK,
    'file' => 'mathjax_conf.inc',
  );

  return $items;
}
